hiretutor/hireapp/urls.py
from django.urls import include, path
from .views import hireapp, tutor, guardian

urlpatterns = [
    path('', hireapp.index, name='home'),

    path('guardian/', include(([
                                   path('guardianhomepage/', guardian.GuardianHomepage,
                                        name='guardian_homepage'),
                                   path('guardianprofile/', guardian.GuardianProfile.as_view(),
                                        name='guardian_profile'),

                               ], 'hireapp'), namespace='guardian')),
    path('tutor/', include(([
                                path('tutorhomepage/', tutor.TutorHomepage,
                                     name='tutor_homepage'),
                                path('tutorprofile/', tutor.TutorProfile.as_view(),
                                     name='tutor_profile'),

                            ], 'hireapp'), namespace='tutor')),
]

hiretutor/hiretutor/urls.py
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static
from hireapp.views import hireapp, guardian, tutor
from django.contrib import admin

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('hireapp.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('accounts/signup/guardian/', guardian.GuardianSignUpView.as_view(), name='guardian_signup'),
    path('accounts/signup/tutor/', tutor.TutorSignUpView.as_view(), name='tutor_signup'),
]
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

hiretutor/templates/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">

    <title>{% block title %}
        {% endblock title %}</title>

    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <!-- Link to your css file -->
    <link rel="stylesheet" href="{% static 'css/mm.css' %}">
    <link rel="icon" href="{% static 'img/nn.ico' %}">
    <link href="https://fonts.googleapis.com/css?family=Baloo" rel="stylesheet">

    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css"
          integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <link href="https://fonts.googleapis.com/css?family=Concert+One" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Bungee" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Baloo+Bhaina" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Gloria+Hallelujah" rel="stylesheet">
    <link href="https://unpkg.com/ionicons@4.5.5/dist/css/ionicons.min.css" rel="stylesheet">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.6.3/css/all.css"
          integrity="sha384-UHRtZLI+pbxtHCWp1t77Bi1L4ZtiqrqD80Kn4Z8NTSRyMA2Fd33n5dQ8lWUE00s/" crossorigin="anonymous">
</head>
<body>
<nav class="navbar navbar-expand-lg navbar-light bg-light">
    <div class="container">
        <a class="navbar-brand" href="{% url 'home' %}"> Hire Your Tutor</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbar1"
                aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbar1">
            <ul class="navbar-nav ml-auto">
                <li class="nav-item active">
                    <a class="nav-link" href="{% url 'home' %}">Home <span
                            class="sr-only">(current)</span></a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href=""> About Us </a>
                </li>
                {% if user.is_authenticated %}
                <li class="nav-item dropdown active">
                    <a class="nav-link  dropdown-toggle" href="#" data-toggle="dropdown"> {{ user.username }} </a>
                    <ul class="dropdown-menu">
                        <li><a class="dropdown-item" href="#">Change Password</a></li>
                        <li><a class="dropdown-item"
                               href="{% if user.is_tutor %}{% url 'tutor:tutor_profile' %}{% else %}{% url 'guardian:guardian_profile' %}{% endif %}">Create Post</a>
                        </li>
                        <li><a class="dropdown-item" href="{% url 'logout' %}">Logout</a></li>
                    </ul>
                </li>
                {% else %}
                <li class="nav-item">
                    <a class="btn ml-2 btn-warning" href="{% url 'login' %}">Login</a>
                </li>
                {% endif %}
            </ul>
        </div>
    </div>
</nav>

<div class="container">
    {% block content %}

    {% endblock content %}

</div>

<!-- Footer -->
<footer class="page-footer font-small blue">

    <!-- Copyright -->
    <div class="footer-copyright text-center py-3">© 2019 Copyright:
        <a href="#">Hire Your Tutor</a>
    </div>
    <!-- Copyright -->

</footer>
<!-- Footer -->

<script src="https://code.jquery.com/jquery-3.2.1.slim.min.js"
        integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN"
        crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js"
        integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q"
        crossorigin="anonymous"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"
        integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl"
        crossorigin="anonymous"></script>


<!-- do not forget download jquery (http://jquery.com/download/)-->
<script src="{% static 'js/jquery-3.3.1.min.js' %}"></script>
<!-- do not forget download popper.js (https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.3/umd/popper.min.js) -->
<script src="{% static 'js/popper.min.js' %}"></script>
<script src="{% static 'js/bootstrap.min.js' %}"></script>
<script type="text/javascript">
$(function() {
    $('[data-toggle="tooltip"]').tooltip();
})




</script>
<script src="https://code.jquery.com/jquery-3.2.1.slim.min.js"
        integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN"
        crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.11.0/umd/popper.min.js"
        integrity="sha384-b/U6ypiBEHpOf/4+1nzFpr53nxSS+GLCkfwBdFNTxtclqqenISfwAzpKaMNFNmj4"
        crossorigin="anonymous"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta/js/bootstrap.min.js"
        integrity="sha384-h0AbiXch4ZDo7tp9hKZ4TsHbi047NrKGLO3SEJAg45jXxnGIfYzk4Si90RDIqNm1"
        crossorigin="anonymous"></script>
<script src="https://unpkg.com/ionicons@4.5.5/dist/ionicons.js"></script>
</body>
</html>

hiretutor/templates/mainbase.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <title>{% block title %}

    {% endblock title %}</title>


    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <!-- Link to your css file -->
    <link rel="icon" href="{% static 'img/nn.ico' %}">

</head>

<body>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <a class="navbar-brand" href="#">Navbar</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
        aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav mr-auto">
            <li class="nav-item active">
                <a class="nav-link" href="#">Home <span class="sr-only">(current)</span></a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="#">Link</a>
            </li>
            <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown"
                aria-haspopup="true" aria-expanded="false">
                Dropdown
            </a>
            <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                <a class="dropdown-item" href="#">Action</a>
                <a class="dropdown-item" href="#">Another action</a>
                <div class="dropdown-divider"></div>
                <a class="dropdown-item" href="#">Something else here</a>
            </div>
        </li>
        <li class="nav-item">
            <a class="nav-link disabled" href="#">Disabled</a>
        </li>
    </ul>
    <form class="form-inline my-2 my-lg-0">
        <a href=""></a>
        <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
        <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
    </form>
</div>
</nav>
<div class="container">

</div>


<!-- do not forget download jquery (http://jquery.com/download/)-->
<script src="{% static 'js/jquery-3.3.1.min.js' %}"></script>
<!-- do not forget download popper.js (https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.3/umd/popper.min.js) -->
<script src="{% static 'js/popper.min.js' %}"></script>
<script src="{% static 'js/bootstrap.min.js' %}"></script>
<script type="text/javascript">
$(function () {
    $('[data-toggle="tooltip"]').tooltip();
})

</script>
</body>
</html>